# Generated by Django 3.2.5 on 2021-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('bike_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('last_ride', models.TimeField(auto_now=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
