# Generated by Django 3.2.5 on 2021-08-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='helmet_in',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikes',
            name='in_danger',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
