# Generated by Django 3.2.5 on 2021-08-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20210807_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='being_used',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
