# Generated by Django 3.2.5 on 2021-08-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_bikes_being_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='in_use',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
